version: '3.5'
services:
  API_CONTAINER_NAME:
    container_name: API_CONTAINER_NAME
    build: .
    image: API_CONTAINER_NAME
    # user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:TRAEFIK_ENV.chas.school"
    env_file:
      - .env
