version: '3.5'
services:
  express_api:
    container_name: express_api
    build: .
    image: express_api
    user: node
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    ports:
      - 7770:7770
    environment:
      - MONGODB_HOST=database
    depends_on:
      - database
    env_file:
      - .env
  database:
    container_name: mongo_db
    image: mongo
    env_file:
      - .env