version: '3.5'

services:
  api:
    image: registry.chas.school/cobalt-api-dev:latest
    working_dir: /app
    command: node dist/server.js
    depends_on:
      - database
    env_file:
      - .env.dev
    networks:
      - traefik
      - backend
    deploy:
      labels:
        traefik.port: '7770'
        traefik.backend: 'cobalt_dev'
        traefik.docker.network: 'traefik'
        traefik.frontend.rule: 'Host:cobalt-api-dev.chas.school'
  database:
    image: mongo:latest
    volumes:
      - database:/database/db
    env_file:
      - .env.dev
    networks:
      - backend
    deploy:
      labels:
        traefik.enable: 'false'

volumes:
  database:

networks:
  traefik:
    external: true
  backend:
    external: false